version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarumae
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=UTC
    ports:
      - "8080:8080"
    networks:
      - tarumae-network
    volumes:
      - ./logs:/app/logs
      - ./downloads:/app/downloads
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  tarumae-network:
    driver: bridge

volumes:
  downloads:
    driver: local
